#!C:/Program\ Files/Git/usr/bin/bash.exe

# This hook is called with the following parameters:
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#

remote="$1"
url="$2"

z40=0000000000000000000000000000000000000000

while read local_ref local_sha remote_ref remote_sha
do
    if [ $remote_ref = 'refs/heads/master' ]
        then
            exec powershell.exe -NoProfile -ExecutionPolicy Bypass -File ".\.git\hooks\Invoke-Notarize-SSH.ps1"
    fi
done

exit 0
