# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# https://github.com/microsoft/action-psscriptanalyzer
# For more information on PSScriptAnalyzer in general, see
# https://github.com/PowerShell/PSScriptAnalyzer

name: Build and Compile Master

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
#  schedule:
#    - cron: '45 16 * * 6'
    
permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    name: PSScriptAnalyzer
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pester Test Report
        uses: zyborg/pester-tests-report@v1.5.0
        with:
          # test_results_path: # optional
          # Comma-separated list of test full names, or with `-like` wildcards, to restrict which tests are resolved.  The default is to include every test discovered matching the other input parameters.
          # full_names_filters: # optional
          include_paths: .\tests\*.Tests.ps1
          # Comma-separated list of tags to include for testing.
          include_tags: Unit
          # Comma-separated list of tags to exclude for testing.
          # exclude_tags: # optional
          # Optionally specify the level of output detail for the test results. May be one of: `none`, `Minimal`, `normal`, `detailed`, `diagnostic` The default is `normal`.
          output_level: detailed
          # The name of the report object that will be attached to the Workflow Run.  Defaults to the name `TEST_RESULTS_<datetime>` where `<datetime>` is in the form `yyyyMMdd_hhmmss`.
          # report_name: # optional
          # The title of the report that will be embedded in the report itself, which defaults to the same as the `report_name` input.
          # report_title: # optional
          # GITHUB_TOKEN to authenticate against API calls to attach report to Workflow Run.
          # github_token: # optional
          # Comma-separated list of one or more directories to scan for code coverage, relative to the root of the project. Will include all .ps1 and .psm1 files under these directories recursively.
          # coverage_paths: # optional
          # The name of the code coverage report object that will be attached to the Workflow Run.  Defaults to the name `COVERAGE_RESULTS_<datetime>` where `<datetime>` is in the form  `yyyyMMdd_hhmmss`.
          # coverage_report_name: # optional
          # The title of the code coverage report that will be embedded in the report itself, which defaults to the same as the `code_coverage_report_name` input.
          # coverage_report_title: # optional
          # If true, will cause the step to fail if one or more tests fails.
          tests_fail_step: true
      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@2044ae068e37d0161fa2127de04c19633882f061
        with:
          # Check https://github.com/microsoft/action-psscriptanalyzer for more info about the options.
          # The below set up runs PSScriptAnalyzer to your entire repository and runs some basic security rules.
          path: .\src
          recurse: true 
          # Include your own basic security rules. Removing this option will run all the rules 
          includeRule: '"PSAvoidGlobalAliases", "PSAvoidUsingConvertToSecureStringWithPlainText"'
          output: results.sarif
      # Upload the SARIF file generated in the previous step
      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
