# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# https://github.com/microsoft/action-psscriptanalyzer
# For more information on PSScriptAnalyzer in general, see
# https://github.com/PowerShell/PSScriptAnalyzer

name: Build and Compile Master

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
#  schedule:
#    - cron: '45 16 * * 6'
    
permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        psversion: [5,7]
        os: [windows-latest]
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    name: Build Master
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup PowerShell module cache ${{ runner.os }}
        if: startsWith( ${{ matrix.os }}, windows- )
        id: cacher
        uses: actions/cache@v3
        with:
          path: |
            C:\Users\runneradmin\Documents\PowerShell\Modules
            C:\Users\runneradmin\Documents\WindowsPowerShell\Modules
          key: ${{ runner.os }}-${{ matrix.psversion }}-ConnectMS365
      - name: Trust PSGallery
        shell: powershell
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
      - name: Bootstrap environment dependencies
        if: steps.cacher.outputs.cache-hit != 'true'
        run: .\build.ps1 -Bootstrap
        shell: powershell
      - name: Compile Module
        run: .\build.ps1 Compile
        shell: powershell
      - name: Upload Compile Output
        uses: actions/upload-artifact@v3
        with:
          name: Connect-MS365_${{ runner.os }}_${{ matrix.psversion }}
          path: .\BuildOutput\Connect-MS365\*
        if: ${{ always() }}
      - name: PSScriptAnalyzer
        shell: powershell
        run: .\build.ps1 Analyze
      - name: Pester Unit
        shell: powershell
        run: |
          $VerbosePreference = "Continue"
          .\build.ps1 PesterUnit
      - name: Upload Pester Unit Test Results
        uses: actions/upload-artifact@v3
        with:
          name: windows-Unit-Tests
          path: .\BuildOutput\testResultsUnit.xml
      - name: Create Help Files
        shell: powershell
        run: |
          .\build.ps1 CreateMDHelp
          .\build.ps1 UpdateMDHelp
          .\build.ps1 CreateExternalHelp
      - name: Build Package
        shell: powershell
        run: .\build.ps1 Build
      - name: Pester Integration
        shell: powershell
        run: |
          $VerbosePreference = "Continue"
          .\build.ps1 PesterIntegration
      - name: Upload Pester Integration Test Results
        uses: actions/upload-artifact@v3
        with:
          name: windows-Integration-Tests
          path: .\BuildOutput\testResultsIntegration.xml
