# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# https://github.com/microsoft/action-psscriptanalyzer
# For more information on PSScriptAnalyzer in general, see
# https://github.com/PowerShell/PSScriptAnalyzer

name: Build and Compile Master

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
#  schedule:
#    - cron: '45 16 * * 6'
    
permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        psversion: [5]
        os: [windows-latest]
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    name: Build Master
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Bootstrap environment dependencies
        run: .\build.ps1 -Bootstrap
        shell: powershell
      - name: Compile Module
        run: .\build.ps1 Compile
        shell: powershell
